
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 2235;
const int acc_off_y = 728;
const int acc_off_z = -1890;
const float acc_scale_x = 15969.288954;
const float acc_scale_y = 16522.425955;
const float acc_scale_z = 16949.923924;

const int magn_off_x = 1;
const int magn_off_y = -98;
const int magn_off_z = -64;
const float magn_scale_x = 227.405369;
const float magn_scale_y = 230.417370;
const float magn_scale_z = 243.300731;
