
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 2337;
const int acc_off_y = 710;
const int acc_off_z = -1618;
const float acc_scale_x = 14081.707739;
const float acc_scale_y = 17090.488545;
const float acc_scale_z = 17384.648810;

const int magn_off_x = 2;
const int magn_off_y = -97;
const int magn_off_z = -62;
const float magn_scale_x = 207.753806;
const float magn_scale_y = 212.675798;
const float magn_scale_z = 226.268787;
